# configs/data_configs/mnist_config.yaml
data:
  name: Xray
  raw_data_path: data/01.원천데이터
  test_data_path: data/01.원천데이터
  # processed_data_path: data/processed/Sketch #어차피 안씀; 왜 있는거지
  train_df_path: data/train.csv
  test_df_path: data/train.csv
  train_val_split: 0.8
  val_test_split: 0.7
  batch_size: 8
  num_workers: 16
  pin_memory: true
