# configs/data_configs/mnist_config.yaml
data:
  name: Xray
  raw_data_path: /home/vilab/data/Training_Gray
  test_data_path: /home/vilab/data/Training_Gray
  # processed_data_path: data/processed/Sketch #어차피 안씀; 왜 있는거지
  train_df_path: /home/vilab/paper/Xray_module_classification/data/train.csv
  test_df_path: /home/vilab/paper/Xray_module_classification/data/train.csv
  train_val_split: 0.8
  val_test_split: 0.7
  batch_size: 64
  num_workers: 32
  pin_memory: true
