# configs/augmentation_configs/Xray_augmentation.yaml
augmentation:
  use_augmentation: False
  transforms:
    # - name: ColorJitter
    #   params:
    #     brightness: 0.5
    - name: RandAugment
      params:
        num_ops: 2
        magnitude: 9
