data_module: "src.data.custom_datamodules.Xray_datamodule.XrayDataModule"
model_module: "src.plmodules.XrayModel2.XrayModel2"

data_config_path: "configs/data_configs/Xray_config.yaml"
augmentation_config_path: "configs/augmentation_configs/Xray_augmentation.yaml"

sweep_path: "configs/train_configs/train/sweep.yaml"
use_sweep: False #sweep 사용시 True 로.(default 는 False)

model:
  model_name: "convnext_xxlarge"
  num_classes: 474 ##473(max_num) +1
  pretrained: True
  num_classes_model1: 242  # 일반 물품
  num_classes_model2: 136  # 위해 물품
  num_classes_model3: 19   # 정보 저장 매체

optimizer:
  name: Adam
  params:
    lr: 2e-4

scheduler:
  name: StepLR
  params:
    step_size: 1
    gamma: 0.7

trainer:
  max_epochs: 20
  accelerator: gpu
  devices: [7,8,9]  # Specify the exact GPU indices 
  default_root_dir: "output" #output 폴더에 결과 자동으로 추가.
  # strategy : "ddp" 


callbacks:
  model_checkpoint:
    monitor: val_acc
    save_top_k: 3
    mode: max
  early_stopping:
    monitor: val_acc
    patience: 10
    mode: max

wandb_name: "convnext_router1"



# Attention 시각화 설정 추가
visualize_attention: True
attention:
  input_image_dir: "data/train"
  output_image_dir: "output/Transformer"
  layer_index: 23
  head_index: 7