data_module: "src.data.custom_datamodules.Xray_datamodule.XrayDataModule"
model_module: "src.plmodules.XrayModelModule.XrayModelModule"

data_config_path: "configs/data_configs/Xray_config.yaml"
augmentation_config_path: "configs/augmentation_configs/Xray_augmentation.yaml"

sweep_path: "configs/train_configs/train/sweep.yaml"
use_sweep: True #sweep 사용시 True 로.(default 는 False)

model:
  model_name: "swin_large_patch4_window7_224"
  num_classes: 469
  pretrained: True

optimizer:
  name: Adam
  params:
    lr: 2e-4

scheduler:
  name: StepLR
  params:
    step_size: 1
    gamma: 0.7

trainer:
  max_epochs: 100
  accelerator: gpu
  devices: 4 
  default_root_dir: "output" #output 폴더에 결과 자동으로 추가.
  strategy : "ddp" 


callbacks:
  model_checkpoint:
    monitor: val_acc
    save_top_k: 3
    mode: max
  early_stopping:
    monitor: val_acc
    patience: 100
    mode: max

wandb_name: "paper"



# Attention 시각화 설정 추가
visualize_attention: True
attention:
  input_image_dir: "data/train"
  output_image_dir: "output/Transformer"
  layer_index: 23
  head_index: 7